export const ROUTER_PATH = {
	HOMEPAGE: '/',
	ADMIN: '/admin',
	LOGIN: '/login',
	VOTING: '/voting',
	RESULT: '/result',
	LIST_CAMPAIGN: '/list-campaign',
	CREATE_CAMPAIGN: '/create-campaign',
	EDIT_CAMPAIGN: '/edit-campaign',
	WITHDRAW: '/withdraw',
	HISTORY: '/history',
	TOKENS: '/tokens',
	PROFILE: '/profile',
	CREATE_PROFILE: '/create-profile',
	EDIT_PROFILE: '/edit-profile',
}
